// @path: @/app/layout.tsx
// Bootstrap для стилізації компонентів
import "bootstrap/dist/css/bootstrap.css";
// для додаткового налаштування стилів застосунку
import "./globals.css";
//  типи та компоненти для роботи з метаданими та шрифтами
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "./head";
import Script from "next/script";
// забезпечує глобальний Toaster для виведення toast-повідомлень
import { GlobalProvider } from "./GlobalProvider";
// ля відображення заголовку та підвалу сторінки
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
// екземпляр шрифту Inter з підмножиною латинських символів
const inter = Inter({ subsets: ["latin"] });
// об'являємо метадані застосунку
export const metadata:Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// компонент, який визначає загальний макет сторінки
export default function RootLayout({ children }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* для керування метаданими сторінки */}
      <Head />
      {/* визначаємо тіло сторінки */}
      <body className={inter.className}>
        {/* загальний провайдер для включення глобального Toaster */}
        <GlobalProvider>
          {/* для відображення верхньої частини сторінки */}
            <Header />
          {/* контент, який буде відображений на сторінці */}
            {children}
          {/* для відображення нижньої частини сторінки */}
            <Footer />
        </GlobalProvider>

        {/* підключаємо скрипти для роботи Bootstrap та іконок FontAwesome */}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://kit.fontawesome.com/9edb65c86a.js"></Script>
      </body>
    </html>
  );
}
